language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
    - sed -iz 's/DATABASES[^}]*./DATABASES = {\n    'default': {\n        'ENGINE': 'django.db.backends.sqlite3',\n        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),\n    }/g' automata_life_server/settings.py 
# command to run tests
script:
    - python manage.py test
    - python manage.py harvest
