language: python
sudo: required
dist: trusty
python:
    - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
    - ./.travis_settings/setup.sh
# command to run tests
script:
    - python manage.py test
    - python manage.py harvest
